- name: Playbook for debug
  hosts:
  vars:
        URL: "www.ganesh.com"
  tasks:
      - name: print hellow world
        debug:
        msg: "Please visit this {{URL}}"
      - name: print hellow world
        debug:
        msg: "Please visit this {{URL}}"
      - name: print hellow world
        debug:
        msg: "Please visit this {{URL}}"
        vars:
             URL: "www.cloudblitzs.com"