- name: Install Java
  yum:
    state: latest
    name: java

- name: Download tomcat 8
  get_url:
    url: "{{ TOMCAT_URL }}"
    dest: /opt/

- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/
    remote_src: true

- name: start service
  shell: /opt/{{TOMCAT_NAME}}/bin/catalina.sh start

- name: Deploy webapp
  copy:
    src: ./student.war
    dest: /opt/{{TOMCAT_NAME}}/webapps/student.war
   
- name: Upload configuration file
  copy:
    src: ./context.xml
    dest: /opt/{{TOMCAT_NAME}}/conf/context.xml

- name: Store my-sql connector in lib
  get_url:
    url: '{{MYSQL_LIB_URL}}'
    dest: /opt/{{TOMCAT_NAME}}/lib/